version: '3'

networks:
  postgres:
    driver: bridge

services:
  bank-db:
    container_name: bank-db
    image: postgres:14.5
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
    networks:
      - postgres
  bank:
    build: .
    environment:
      DATASOURCE_HOST: bank-db
    ports:
      - 8080:8080
    depends_on:
      - bank-db
    networks:
      - postgres
